### ISSUE TITLE
Feedstock was never built

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/sphinx-testing-feedstock#1]
CC @conda-forge/core

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-smithy/issues/1154

**Comment by asmeurer** [comment]
@conda-forge-admin, please rerender

**Comment by sodre** [comment]
@asmeurer, 
You can force a rebuild of the master branch in this case. My suggestion is to:

1. Clone the `sphinx-testing-feedstock`
1. Push an empty commit. In newer versions of git you can do that with:
  ```git commit --allow-empty -m 'force rebuild' && git push```
  For older versions of git we can use the `--amend`: 
  ```git commit --amend --no-edit && git push --force```

@isuruf, I would do the empty commit myself, but I don't have permission to commit to repos outside the ones I maintain yet.

**Comment by isuruf** [comment]
I manually triggered a build

**Comment by asmeurer** [comment]
Thanks. I guess the rerender bot is also broken?

**Comment by isuruf** [comment]
I think the rerender bot doesn't comment on an issue if there's no rerender needed. Can't remember exactly.

**Comment by asmeurer** [comment]
It hasn't been that way in the past https://github.com/conda-forge/emacs-feedstock/pull/31#issuecomment-490696823. It definitely useful if it comments regardless so you know that it is working.

**Comment by isuruf** [comment]
That's a pull request. Do you have an example in an issue?

**Comment by isuruf** [comment]
> It definitely useful if it comments regardless so you know that it is working.

I agree. I just don't have the time to do it myself.

**Comment by asmeurer** [comment]
Does the rerender bot not work in issue comments? I would expect it to.

**Comment by scopatz** [comment]
It does
